### ISSUE TITLE
A few suggestions 

### ISSUE THREAD

**Issue by Gabilon** [Jpadilla1/chatrooms#2]
1. Instead of 10 seconds it should be at the moment once a message has been sent.
2. Instead of pressing the button send, a good option would be once it hits "Enter" on the keyboard it sends automatically the message.
3. While on another tab on my web browser, it would be convenient to show on the chat-room tab to show a small message saying: "New Message from [Chat-room group].  
4.  Having a user the ability to create it's own chat-room would be a good idea.  I would recommend making it private.  Lets say I have a project to do with 4 members and I want to create a private chat room. 
5. Something convenient would be to have general profile for each user.  And each user can have a limited access to it's users and view their profile.  Options would be:  
     a.  A user can send a private message to another user.
     b.  Invite a user to it's own private chat room.

**Comment by Jpadilla1** [comment]
Ok, I'm going to separate all these issues into separate ones for better discussion on each topic.
- 1. Is on issue #1 
- 2. Is on issue #3
